# Generated by Django 5.2.14 on 2026-05-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coingecko_id', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_price_usd', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('price_change_24h_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_change_24h_usd', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('market_cap_usd', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('volume_24h_usd', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('high_24h_usd', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('low_24h_usd', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('circulating_supply', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('usd_to_inr_rate', models.DecimalField(decimal_places=4, default=83.5, max_digits=10)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-market_cap_usd'],
            },
        ),
    ]
