# Generated by Django 5.2.14 on 2026-05-23 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('deposit', 'Deposit USD'), ('withdraw', 'Withdraw to INR')], max_length=20)),
                ('coin_amount', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('usd_amount', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('inr_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('price_at_time_usd', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('fee_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coins.coin')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
