# Generated by Django 5.2.14 on 2026-05-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=14)),
                ('aadhaar_front', models.ImageField(blank=True, upload_to='kyc/aadhaar/')),
                ('aadhaar_back', models.ImageField(blank=True, upload_to='kyc/aadhaar/')),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('pan_image', models.ImageField(blank=True, upload_to='kyc/pan/')),
                ('selfie_image', models.ImageField(blank=True, upload_to='kyc/selfie/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
