# Generated by Django 5.2.14 on 2026-05-31 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycdocument',
            name='aadhaar_back',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='aadhaar_front',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='pan_image',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='selfie_image',
        ),
    ]
