# Generated by Django 5.2.14 on 2026-05-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_buyrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(help_text='e.g. cryptovault@upi', max_length=200)),
                ('upi_name', models.CharField(help_text='Name shown in UPI apps', max_length=200)),
                ('phone_number', models.CharField(help_text='WhatsApp/contact for payment issues', max_length=20)),
                ('qr_image', models.ImageField(blank=True, help_text='Upload your UPI QR code image', null=True, upload_to='payment/qr/')),
                ('payment_note', models.TextField(default='Include your registered email in payment remarks.', help_text='Instructions shown to user during payment')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
        migrations.AlterField(
            model_name='buyrequest',
            name='transaction_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
