# Generated by Django 5.2.14 on 2026-05-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_paymentsettings_alter_buyrequest_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='account_holder_name',
            field=models.CharField(blank=True, help_text='Name on the bank account', max_length=200),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='account_number',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='bank_branch',
            field=models.CharField(blank=True, help_text='e.g. Connaught Place, New Delhi', max_length=200),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='bank_name',
            field=models.CharField(blank=True, help_text='e.g. State Bank of India', max_length=200),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='ifsc_code',
            field=models.CharField(blank=True, help_text='e.g. SBIN0001234', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='phone_number',
            field=models.CharField(blank=True, help_text='WhatsApp/contact number', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='upi_id',
            field=models.CharField(blank=True, help_text='e.g. cryptovault@upi', max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='upi_name',
            field=models.CharField(blank=True, help_text='Name shown in UPI apps', max_length=200),
        ),
    ]
