# Generated by Django 5.2.14 on 2026-06-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_paymentsettings_account_holder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyrequest',
            name='screenshot',
        ),
    ]
